name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.8.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Publish CLI
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/cli
          pnpm run deploy || if [ "$?" = "403" ] && grep -q "You cannot publish over the previously published versions" <<< "$(cat)"; then echo "Package version already exists, skipping publish"; exit 0; fi

      - name: Publish SDK
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/sdk
          pnpm run deploy || if [ "$?" = "403" ] && grep -q "You cannot publish over the previously published versions" <<< "$(cat)"; then echo "Package version already exists, skipping publish"; exit 0; fi

      - name: Publish Cloud
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/cloud
          pnpm run deploy || if [ "$?" = "403" ] && grep -q "You cannot publish over the previously published versions" <<< "$(cat)"; then echo "Package version already exists, skipping publish"; exit 0; fi
